#!/bin/bash

USERID=$(id -u)

CHECK_ROOT() {

if [ $USERID -ne 0 ]
then
    echo "please run this script with root privilages"
    exit 1
fi

}

VALIDATE(){
    if [ $? -ne 0 ]
    then 
        echo "git is not installed"
    else
        echo "git is installing"
    fi
    exit 1
}

CHECK_ROOT


dnf list installed git

if [ $? -ne 0 ]
then
    echo "git is not installed checking it"
    dnf install git -y
    
    VALIDATE $?
else
    echo "git is already installed nothing to do"
fi

dnf list installed mysql

if [ $? -ne 0 ]
then
    echo "mysql is not installed checking it"
    dnf install mysql -y

    VALIDATE $?
    

else
    echo "mysql installed nothing to do"
fi