#!/bin/bash

USERID=$ (id -u)

if [ $USERID -ne 0 ]
then
    echo "please run this script with root privilages"
    exit 1
fi

dnf list install git

if [ $? -ne 0 ]
then
    echo "git is not installed checking it"
else
    echo "git is already installed nothing to do"